trigger:
  branches:
    include:
      - dev

pool:
  name: LW-Agents

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: "Build"
            inputs:
              command: "build"
              Dockerfile: "$(DOCKER_FILE)"
              repository: "$(IMAGE_NAME)"
              tags: "latest"

          - task: ECRPushImage@1
            displayName: "Publicando a imagem"
            inputs:
              awsCredentials: $(AWS_CREDENTIALS)
              regionName: "us-east-1"
              imageSource: "imagename"
              sourceImageName: "$(IMAGE_NAME)"
              sourceImageTag: "latest"
              repositoryName: "$(REPOSITORY_NAME)"
              pushTag: "latest"
              # autoCreateRepository: true

  - stage: Deploy
    jobs:
      - job: Adjust_vars
        steps:
          - task: Bash@3
            displayName: "Carregando as variáveis"
            inputs:
              targetType: "inline"
              script: |
                echo Iniciando o processo no Shell
                sudo apt-get update
                sudo apt-get install -y jq gettext-base
                source ./azure-settings-portal.sh

                envsubst "\$IMAGE_NAME,\$AWS_ACCOUNT,\$TASK_MEMORY,\$TASK_CPU" < "portal-task-definition.json" > "temp-portal-task.json"
                #env | sort

                cat temp-portal-task.json

      - job: Deploy
        dependsOn: [Adjust_vars]
        steps:
          - task: AWSCLI@1
            displayName: "Registrando a task-definition"
            inputs:
              awsCredentials: $(AWS_CREDENTIALS)
              regionName: "us-east-1"
              awsCommand: "ecs"
              awsSubCommand: "register-task-definition"
              awsArguments: "--cli-input-json file://temp-portal-task.json"
              failOnStandardError: false
          - task: AWSCLI@1
            displayName: "Atualizando o serviço $(IMAGE_NAME)"
            inputs:
              awsCredentials: $(AWS_CREDENTIALS)
              regionName: "us-east-1"
              awsCommand: ecs
              awsSubCommand: "update-service"
              awsArguments: "--cluster $(CLUSTER_NAME) --service $(IMAGE_NAME)-service --task-definition $(IMAGE_NAME) --force-new-deployment  --enable-execute-command"
              failOnStandardError: false
