FROM node:20-alpine as build

WORKDIR /website

COPY ./ /website/

RUN npm install

ENV NEXT_PUBLIC_CONTENTFUL_SPACE_ID=$(NEXT_PUBLIC_CONTENTFUL_SPACE_ID)
ENV NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=$(NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN)
RUN npm run build

EXPOSE 3000

CMD [ "npm", "start"]